#!/usr/bin/env bash
SESSION=consumer-rights-rails
FOLDER=/Users/rlario/Documents/rails-apps/consumer-rights-rails

tmux -2 new-session -d -s $SESSION

# Setup a window for IDE
tmux rename-window -t $SESSION:1 IDE

# Set up the splits
tmux split-window -v
tmux select-pane -t 1
tmux split-window -h

# Provision the splits
tmux select-pane -t 1
tmux send-keys "cd $FOLDER && vim ." C-m
tmux select-pane -t 2
tmux send-keys "cd $FOLDER && be guard -c" C-m
tmux resize-pane -x 80
tmux select-pane -t 3
tmux send-keys "cd $FOLDER && clear" C-m
tmux resize-pane -y 10

# Setup a window for Background Tasks
tmux new-window -t $SESSION:2 -n 'BT'

# Provision the BT Window
tmux split-window -h
tmux select-pane -t 1
tmux send-keys "cd $FOLDER && be rails s" C-m

# Move to IDE window
tmux select-window -t $SESSION:1
# Attach to session
tmux -2 attach-session -t $SESSION
