#!/usr/bin/env bash
SESSION=maliciousmind-github-io
FOLDER=/Users/rlario/Documents/maliciousmind.github.io

tmux -2 new-session -d -s $SESSION

# Setup a window for IDE
tmux rename-window -t $SESSION:1 IDE

# Set up the splits
tmux split-window -h
tmux select-pane -t 2
tmux split-window -v

# Provision the splits
tmux select-pane -t 1
tmux send-keys "cd $FOLDER && vim ." C-m
tmux select-pane -t 2
tmux send-keys "cd $FOLDER && be rake watch" C-m
tmux resize-pane -x 35
tmux select-pane -t 3
tmux send-keys "cd $FOLDER && rake generate" C-m
tmux resize-pane -y 10

# Attach to session
tmux -2 attach-session -t $SESSION
